import SentinelLayout from "@/components/SentinelLayout";
import { useDemo } from "@/contexts/DemoContext";
import { decisionLabel, riskLabel, riskTone, sar } from "@/lib/sentinelUi";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, CircleDashed, PlayCircle, Presentation, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function CommitteeBriefing() {
  const { locale } = useDemo();
  const isAr = locale === "ar";
  const comparison = trpc.sentinel.scenarioComparison.useQuery();
  return <SentinelLayout eyebrow={isAr ? "وضع العرض للجنة" : "COMMITTEE DEMO MODE"} title={isAr ? "مسار عرض SentinelAI" : "SentinelAI demo briefing"}>
    <section className="committee-hero"><div><span className="section-index">10</span><p>{isAr ? "مسار عرض موجّه" : "GUIDED DEMO SEQUENCE"}</p><h2>{isAr ? "اعرض رحلة تقييم المخاطر من المعاملة إلى استدلال الذكاء المحلي والقرار الموحد القابل للمراجعة." : "Show the journey from transaction context to Custom Local AI inference and reviewable unified decision."}</h2><span>{isAr ? "توضح كل بطاقة معالجة سيناريو العرض عبر مسار تقييم موحد يجمع حواجز القواعد واستدلال الذكاء المحلي." : "Each card showcases scenario evaluation through a unified pipeline combining rule guardrails and Custom Local AI inference."}</span></div><div className="committee-seal"><Presentation size={28} /><b>{isAr ? "6 قصص عرض" : "6 DEMO STORIES"}</b><small>{isAr ? "قابلة للتكرار" : "REPLAYABLE"}</small></div></section>
    <section className="committee-flow" aria-label={isAr ? "خطوات عرض اللجنة" : "Committee presentation steps"}><div><span>01</span><b>{isAr ? "اختر سيناريو" : "Choose scenario"}</b><small>{isAr ? "تحميل معطيات ثابتة" : "Load fixed inputs"}</small></div><i /><div><span>02</span><b>{isAr ? "استدلال وتقييم موحد" : "Unified AI & Rules"}</b><small>{isAr ? "قواعد + ذكاء محلي" : "Rules + Local AI"}</small></div><i /><div><span>03</span><b>{isAr ? "افتح الأدلة" : "Open evidence"}</b><small>{isAr ? "ملف تحقيق ومحادثة" : "Case file & chat"}</small></div></section>
    <section className="committee-scenario-grid"><header><div><span>{isAr ? "مقارنة السيناريوهات" : "SCENARIO COMPARISON"}</span><h3>{isAr ? "نتائج محرك التقييم الموحد" : "Unified engine outcomes"}</h3></div><p><ShieldCheck size={15} /> {isAr ? "عرض فقط · لا ينشئ سجلات جديدة" : "Read-only · no new records created"}</p></header>{comparison.isLoading ? <div className="committee-loading"><CircleDashed className="spin" size={18} />{isAr ? "جارٍ تجهيز المقارنة…" : "Preparing comparison…"}</div> : <div className="committee-scenarios">{comparison.data?.map((scenario, index) => <article key={scenario.id} className="committee-scenario-card"><div className="committee-card-number">{String(index + 1).padStart(2, "0")}</div><div className="committee-card-main"><span>{isAr ? scenario.titleAr : scenario.title}</span><p>{isAr ? scenario.description : scenario.description}</p><small>{sar(scenario.input.amount, locale)} · {scenario.input.destinationCountry}</small></div>{scenario.available ? <div className="committee-card-outcome"><b className={`level-pill ${riskTone(scenario.riskLevel)}`}>{riskLabel(scenario.riskLevel, locale)}</b><strong>{decisionLabel(scenario.decision, locale)}</strong><small>{scenario.factors} {isAr ? "عوامل" : "factors"}</small></div> : <div className="committee-card-outcome unavailable"><b>{isAr ? "غير متاح" : "Unavailable"}</b><small>{isAr ? "ملف العميل غير متاح حاليًا" : "Customer profile unavailable"}</small></div>}<Link className="committee-run" href={`/bank?scenario=${encodeURIComponent(scenario.id)}`}><PlayCircle size={17} />{isAr ? "تشغيل" : "Run"}<ArrowRight size={15} /></Link></article>)}</div>}</section>
    <section className="committee-close"><CheckCircle2 size={19} /><div><b>{isAr ? "نقطة حديث مقترحة للجنة" : "Suggested committee talking point"}</b><p>{isAr ? "يعمل SentinelAI كمنظومة ذكاء مخاطر محلية مخصصة ومدرّبة للمهمة؛ يحلل النموذج سياق المعاملة والمؤشرات السلوكية والشذوذ والمعرفة التنظيمية المسترجعة عبر RAG، لتندمج في توصية مخاطر دقيقة، مع بقاء السياسات الإلزامية وحواجز الأمان حاكمة للنتيجة النهائية." : "SentinelAI operates as a task-specific Custom-Trained Local AI risk system; the model analyzes transaction context, behavioral indicators, anomaly signals, and RAG-retrieved regulatory knowledge into an accurate risk recommendation, while mandatory policy guardrails strictly govern the final outcome."}</p></div></section>
  </SentinelLayout>;
}
