export const customerPrivacyPolicy = {
  sectionTitleAr: "خصوصية بيانات العميل",
  sectionTitleEn: "Customer data privacy",
  overviewAr: "تُحفظ بيانات العملية وسجل مراجعتها ضمن بيئة المشروع المخصصة، وتُستخدم فقط لتحليل المخاطر والمراجعة والتدقيق المرتبط بالحالة. يفصل SentinelAI بين حفظ السجل ومسار التحليل المحلي لحماية خصوصية بيانات العميل.",
  overviewEn: "Transaction data and review records are stored within the dedicated project environment, used solely for risk assessment, case review, and audit trails. SentinelAI isolates record retention from the local AI pipeline to protect customer data privacy.",
  points: [
    {
      id: "defined-purpose",
      titleAr: "استخدام محدد",
      titleEn: "Defined purpose",
      textAr: "بيانات العملية تستخدم للتقييم والتحقيق وسجل التدقيق فقط.",
      textEn: "Transaction data is used solely for risk scoring, investigation, and audit trail records.",
    },
    {
      id: "local-processing",
      titleAr: "تحليل محلي عند التفعيل",
      titleEn: "Local processing when enabled",
      textAr: "عند تفعيل Local AI يُعالج سياق التحليل داخل الجهاز، ليبقى ضمن بيئة SentinelAI المخصصة وبعيدًا عن أي مسار ذكاء خارجي غير لازم للعرض.",
      textEn: "When Local AI is enabled, analysis context is processed entirely on-device, keeping it within SentinelAI's dedicated environment and away from any unnecessary external AI pathways.",
    },
    {
      id: "review-retention",
      titleAr: "سجل للمراجعة",
      titleEn: "Review retention",
      textAr: "تحفظ العملية لتمكين المراجع من الرجوع إلى القرار والعوامل المسجلة.",
      textEn: "The operation is saved to enable the reviewer to inspect the decision and recorded factors.",
    },
  ],
  sdaiaReference: {
    id: "sdaia-pdp",
    authority: "SDAIA",
    authorityAr: "سدايا",
    title: "Personal Data Protection",
    titleAr: "حماية البيانات الشخصية",
    cardTitleAr: "سدايا — حماية البيانات الشخصية",
    cardTitleEn: "SDAIA — Personal Data Protection",
    url: "https://sdaia.gov.sa/ar/Research/Pages/DataProtection.aspx",
    statementAr: "يرتكز تصميم SentinelAI على المبادئ الوطنية لحماية البيانات الشخصية لترسيخ حوكمة مسؤولة في معالجة بيانات العمليات المصرفية.",
    statementEn: "SentinelAI's design builds upon national personal data protection principles to establish responsible governance for banking transaction data.",
    principles: [
      {
        id: "purpose-specification",
        titleAr: "تحديد الغرض من استخدام البيانات",
        titleEn: "Purpose specification",
        textAr: "تُعالج بيانات العملية لأغراض تقييم مخاطر التحويل والتحقيق وإعداد سجل التدقيق المعتمد.",
        textEn: "Transaction data is processed for transfer risk evaluation, investigation, and audit trail generation.",
      },
      {
        id: "data-minimization",
        titleAr: "تقليل البيانات إلى الحد اللازم",
        titleEn: "Data minimization",
        textAr: "يقتصر جمع واستخدام البيانات على العناصر الضرورية لإصدار القرار ومراجعة الحالة بدقة وكفاءة.",
        textEn: "Data collection and usage are focused on essential elements required for decisioning and case review.",
      },
      {
        id: "retention-period",
        titleAr: "مدة الاحتفاظ",
        titleEn: "Retention period",
        textAr: "تُحفظ سجلات وسياقات العمليات لفترات محددة تخدم متطلبات المراجعة والتدقيق والحوكمة المصرفية.",
        textEn: "Transaction records and context snapshots are retained for defined operational periods serving review, audit, and governance.",
      },
      {
        id: "protection-measures",
        titleAr: "إجراءات الحماية التنظيمية والإدارية والتقنية",
        titleEn: "Organizational, administrative & technical protection measures",
        textAr: "تطبيق ضوابط التشفير وعزل البيئات والتحكم بالصلاحيات بحسب الدور لحماية سرية وسلامة البيانات.",
        textEn: "Enforcing encryption, environment isolation, and role-based access control to safeguard data confidentiality and integrity.",
      },
    ],
    alignmentTypeAr: "تركيز المواءمة",
    alignmentTypeEn: "Alignment focus",
    governanceRoleAr: "مرجع حوكمة داعم",
    governanceRoleEn: "Supporting governance reference",
    boundaryAr: "تطبيق مبادئ حماية البيانات وتحديد الغرض والحد الأدنى من البيانات وإجراءات الأمان التقنية والإدارية.",
    boundaryEn: "Applying data protection principles, purpose specification, data minimization, and technical and administrative safeguards.",
    disclaimerAr: "مرجع حوكمة داعم يوجه أفضل ممارسات حماية البيانات الشخصية والخصوصية في بيئة العمليات المصرفية.",
    disclaimerEn: "A supporting governance reference guiding best practices for personal data protection and privacy in banking operations.",
  },
  operationsWorkspaceNoteAr: "بيانات هذه العملية خاصة ومحفوظة للمراجعة داخل SentinelAI.",
  operationsWorkspaceNoteEn: "This operation’s data is private and retained within SentinelAI for review.",
} as const;
