import SentinelLayout from "@/components/SentinelLayout";
import { useDemo } from "@/contexts/DemoContext";
import { AuditStartPanel } from "@/components/AuditStartPanel";
import { countryLabel, decisionAssessmentExplanation, decisionLabel, riskLabel, riskTone, sar } from "@/lib/sentinelUi";
import { ArrowUpRight, BrainCircuit, ChevronRight, CircleGauge, Fingerprint, ShieldCheck, Sparkles } from "lucide-react";
import { summarizeResultSources } from "@/lib/resultSources";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

export default function Home() {
  const { locale, results, current } = useDemo();
  const isAr = locale === "ar";
  const persistedResults = trpc.sentinel.persistedResults.useQuery();
  const resultSources = summarizeResultSources(results, persistedResults.data ?? []);
  const decisionResults = resultSources.unified;
  const highRisk = decisionResults.filter(item => item.decision !== "Approve").length;
  const avgScore = decisionResults.length ? Math.round(decisionResults.reduce((sum, item) => sum + item.score, 0) / decisionResults.length) : 0;
  return <SentinelLayout eyebrow={isAr ? "ذكاء مخاطر محلي · تقييم موحّد ومحكوم" : "PROPRIETARY LOCAL RISK AI · UNIFIED GOVERNED ASSESSMENT"} title={isAr ? "مركز رصد وتقييم المخاطر الذكي" : "Intelligent Risk Command Center"}>
    <section className="hero-panel">
      <div className="hero-copy"><p className="hero-kicker"><Fingerprint size={15} /> {isAr ? "سياق التحويل · إشارات الخطر · ذكاء محلي خاص" : "Transfer context · Risk signals · Custom Local AI"}</p><h2>{isAr ? <>ذكاء مخاطر يدمج<br /><em>الإشارات</em><br />في توصية قابلة<br />للمراجعة.</> : <>Risk intelligence combining<br /><em>signals</em><br />into a reviewable<br />recommendation.</>}</h2><p>{isAr ? "تجمع SentinelAI تحليل السلوك والشذوذ والقواعد والسياق التنظيمي واستدلال نموذج ذكاء محلي خاص ومدرّب للمهمة في تقييم موحد للمخاطر، ضمن حواجز سياسة واضحة." : "SentinelAI combines behaviour and anomaly analysis, rules, regulatory context, and task-specific Custom-Trained Local AI inference into a unified risk assessment under clear policy guardrails."}</p><div className="hero-actions"><Link href="/bank" className="primary-button">{isAr ? "فتح بوابة البنك" : "Open bank intake"}<ArrowUpRight size={18} /></Link><Link href="/methodology" className="secondary-button">{isAr ? "كيف يعمل؟" : "View methodology"}</Link></div></div>
      <div className="equation-card"><div className="equation-top"><CircleGauge size={18} /><span>COMPOSITE DECISION POLICY</span></div><div className="equation"><strong className="equation-outcome-badge">outcome</strong><b>=</b><small>AI<br />recommendation</small><b>+</b><small>rule<br />floor</small><strong className="equation-sigma">Σ</strong></div><div className="equation-foot"><span>behaviour evidence</span><i>mandatory policy guardrails</i></div></div>
    </section>
    <section className="metric-strip"><Metric label={isAr ? "محفوظ في Sentinel" : "Saved in Sentinel"} value={String(resultSources.persisted).padStart(2, "0")} accent="cyan" /><Metric label={isAr ? "نتائج هذه الجلسة" : "This session"} value={String(resultSources.sessionOnly).padStart(2, "0")} accent="pink" /><Metric label={isAr ? "متوسط المخاطر" : "Average policy risk"} value={`${avgScore}/100`} accent="ink" /><Metric label={isAr ? "حالة النظام" : "System integrity"} value={isAr ? "سليم" : "Sound"} accent="mint" /></section>
    {resultSources.sessionOnly > 0 ? <p className="session-source-note">{isAr ? "نتائج الجلسة تظهر مؤقتًا حتى يتجدد السجل الدائم؛ زر «جلسة جديدة» لا يحذف أي عملية محفوظة." : "Session results remain visible until the durable record refreshes; New session never deletes saved operations."}</p> : null}
    <section className="dashboard-grid"><div className="panel recent-panel"><div className="panel-head"><div><span className="section-index">02</span><h3>{isAr ? "آخر القرارات المحفوظة" : "Latest stored decisions"}</h3></div><Link href="/analysis" className="cases-link">{isAr ? "عرض كل العمليات" : "View all operations"}<ChevronRight size={15} /></Link></div>{decisionResults.length ? <div className="result-list">{decisionResults.slice(0, 4).map(result => <Link key={result.id} href={`/investigation?id=${encodeURIComponent(result.id)}`} className="result-row"><div className={"decision-orb " + riskTone(result.riskLevel)}>{result.score}</div><div className="result-main"><b>{isAr ? result.snapshot.customer.nameAr : result.snapshot.customer.name}</b><span>{sar(result.snapshot.transaction.amount, locale)} · {countryLabel(result.snapshot.transaction.destinationCountry, locale)}</span></div><div className="result-decision"><span>{decisionLabel(result.decision, locale)}</span><small>{riskLabel(result.riskLevel, locale)}</small></div><ChevronRight size={16} /></Link>)}</div> : <EmptyState isAr={isAr} />}</div>
      <div className="panel model-panel"><div className="panel-head"><div><span className="section-index">03</span><h3>{isAr ? "مسار التقييم الموحد والاستدلال المحلي" : "Unified Assessment & Local AI Pipeline"}</h3></div><BrainCircuit size={19} /></div><div className="separation-map"><div><ShieldCheck size={18} /><span>{isAr ? "محرك القواعد والحواجز" : "Rule Engine & Guardrails"}</span><b>{isAr ? "حد الأمان والسياسة الإلزامية" : "Policy floors & safety bounds"}</b></div><div><Sparkles size={18} /><span>{isAr ? "تحليل السلوك وكشف الشذوذ" : "Behavior & Anomaly Signals"}</span><b>{isAr ? "تغذية نموذج الذكاء المحلي" : "Feeds Custom Local AI"}</b></div><div><Fingerprint size={18} /><span>{isAr ? "استدلال الذكاء المحلي الخاص" : "Custom-Trained Local AI"}</span><b>{isAr ? "توصية مخاطر دقيقة وقابلة للمراجعة" : "Reviewable risk recommendation"}</b></div></div><p className="model-note">{isAr ? "يشارك نموذج الذكاء المحلي المدرّب للمهمة في تحليل سياق المعاملة والأنماط المعقدة ضمن مسار موحد؛ وتندمج توصيته مع القواعد الرقابية دون الإخلال بحدود الأمان أو السياسات الملزمة." : "The task-specific Local AI model analyzes complex transaction context and patterns within a unified pipeline; its recommendation fuses with regulatory rules while mandatory safety floors and compliance guardrails remain governing."}</p></div></section>
    {current && <section className="focus-ribbon"><span>{isAr ? "آخر تحليل" : "LATEST ANALYSIS"}</span><b>{decisionLabel(current.decision, locale)} · {current.score}/100</b><p>{isAr ? (current.policyOverrideAr ?? decisionAssessmentExplanation(current.mlSignal.explanationAr, locale)) : (current.policyOverride ?? decisionAssessmentExplanation(current.mlSignal.explanation, locale))}</p><Link href="/analysis">{isAr ? "فتح التحليل" : "Inspect result"}<ChevronRight size={15} /></Link></section>}
  </SentinelLayout>;
}

function Metric({ label, value, accent }: { label: string; value: string; accent: string }) { return <div className={"metric " + accent}><span>{label}</span><b>{value}</b><i /></div>; }
function EmptyState({ isAr }: { isAr: boolean }) { return <AuditStartPanel compact icon={Fingerprint} eyebrow={isAr ? "مسار العرض" : "DEMO SEQUENCE"} title={isAr ? "ابدأ بسجل قرار جديد" : "Start a new decision record"} description={isAr ? "كل سيناريو ينشئ لقطة مستقلة قابلة للمراجعة." : "Every scenario creates an isolated, reviewable decision snapshot."} steps={isAr ? ["اختر سيناريو", "شاهد مراحل الفحص", "راجع القرار"] : ["Choose a scenario", "Watch live analysis", "Review the decision"]} action={isAr ? "فتح سيناريوهات العرض" : "Open demo scenarios"} href="/bank" />; }
