import SentinelLayout from "@/components/SentinelLayout";
import { useDemo } from "@/contexts/DemoContext";
import { governanceReferencesFor } from "@shared/regulatoryReferences";
import { BrainCircuit, Braces, ExternalLink, FileLock2, Landmark, Lock, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogTitle } from "@/components/ui/dialog";
import { methodologyStandards } from "./methodologyStandards";
import { customerPrivacyPolicy } from "./customerPrivacy";
import { DecisionQualityEvidencePanel } from "@/components/DecisionQualityEvidencePanel";

const stages = [
  ["Intake validation", "التحقق من الإدخال"], ["Context snapshot", "لقطة السياق"], ["Customer profile", "ملف العميل"], ["Baseline comparison", "مقارنة خط الأساس"], ["Amount policy", "سياسة المبلغ"], ["Destination corridor", "ممر الوجهة"], ["Beneficiary relationship", "علاقة المستفيد"], ["Website intelligence", "ذكاء الموقع"], ["Behaviour analysis", "تحليل السلوك"], ["Multi-signal composition", "تجميع إشارات المخاطر"], ["Custom Local AI analysis", "تحليل الذكاء المحلي المخصص"], ["Regulatory context & RAG", "السياق التنظيمي وRAG"], ["Unified risk assessment", "التقييم الموحد للمخاطر"], ["Risk recommendation & audit", "توصية المخاطر وسجل التفسير"],
];
const stageGroups = [
  { en: "Ingest & Context", ar: "تهيئة البيانات والسياق", range: "01—04", indices: [0, 1, 2, 3] },
  { en: "Rules & Policy Signals", ar: "إشارات القواعد والسياسات", range: "05—08", indices: [4, 5, 6, 7] },
  { en: "Local AI & RAG Inference", ar: "الذكاء المحلي واسترجاع RAG", range: "09—11", indices: [8, 9, 10] },
  { en: "Unified Assessment & Audit", ar: "التقييم الموحد والتدقيق", range: "12—14", indices: [11, 12, 13] },
];
const pipelineSteps = [
  { en: "Transaction", ar: "المعاملة" },
  { en: "Data & Behavioural Analysis", ar: "تحليل البيانات والسلوك" },
  { en: "Risk Signals", ar: "إشارات المخاطر" },
  { en: "Custom Local AI Analysis", ar: "تحليل الذكاء المحلي المخصص" },
  { en: "Regulatory Context / RAG", ar: "السياق التنظيمي / RAG" },
  { en: "Unified Risk Assessment", ar: "التقييم الموحد للمخاطر" },
  { en: "Risk Recommendation", ar: "توصية المخاطر" },
  { en: "Explanation & Audit", ar: "التفسير والتدقيق" },
];
export default function Methodology() {
  const { locale } = useDemo(); const isAr = locale === "ar";
  const references = governanceReferencesFor();
  const [externalReference, setExternalReference] = useState<{ url: string; label: string } | null>(null);
  return <SentinelLayout eyebrow={isAr ? "معمارية الذكاء الاصطناعي والحوكمة" : "PROPRIETARY LOCAL AI & GOVERNANCE ARCHITECTURE"} title={isAr ? "كيف يقيّم SentinelAI المخاطر ويتخذ القرار؟" : "How SentinelAI assesses risk & reaches decisions"}>
    <section className="method-hero method-hero-spotlight"><div><p className="hero-kicker"><Braces size={15} /> {isAr ? "نموذج ذكاء محلي خاص ضمن تقييم مخاطر محكوم" : "PROPRIETARY CUSTOM-TRAINED LOCAL AI WITHIN GOVERNED RISK ASSESSMENT"}</p><h2>{isAr ? <>الذكاء المحلي<br />المدرّب يقيّم<br />المخاطر.<br />والسياسة تحمي <em>النتيجة.</em></> : <>Custom-Trained Local AI<br />assesses risk.<br />Policy protects <em>the outcome.</em></>}</h2><p>{isAr ? "تجمع رحلة التحليل سياق التحويل، والسلوك والشذوذ، وإشارات القواعد، والمعرفة التنظيمية، واستدلال نموذج الذكاء المحلي الخاص والمدرب للمهمة. تندمج هذه الطبقات في تقييم موحد للمخاطر وتوصية قابلة للمراجعة ضمن حدود السياسة." : "The analysis journey combines transfer context, behaviour and anomaly detection, rule signals, regulatory knowledge, and task-specific proprietary Local AI inference. These layers fuse into a unified risk assessment and reviewable recommendation within policy bounds."}</p></div><div className="method-diagram"><span>{isAr ? "تحويل" : "Transfer"}</span><i /><span>{isAr ? "إشارات خطر" : "Risk signals"}</span><i className="dashed" /><span>{isAr ? "ذكاء محلي خاص + RAG" : "Custom Local AI + RAG"}</span><i /><span>{isAr ? "تقييم موحد" : "Unified assessment"}</span></div></section>
    <section className="principle-grid methodology-principles"><Principle icon={<FileLock2 />} title={isAr ? "لقطة سياق ثابتة" : "Immutable context snapshot"} text={isAr ? "تُثبّت بيانات المعاملة وملف العميل بالكامل قبل بدء التقييم لضمان بقاء التحقيق واستدلال الذكاء مرتبطين بسجل واحد غير قابل للتعديل." : "Transaction and customer context is frozen prior to scoring, ensuring investigation and Local AI inference remain permanently bound to one immutable record."} /><Principle icon={<BrainCircuit />} title={isAr ? "نموذج ذكاء محلي خاص ومدرّب للمهمة" : "Proprietary Custom-Trained Local AI"} text={isAr ? "ينفذ النموذج استدلالاً محلياً آمناً وفائق الكفاءة (Local AI Inference) يحلل مؤشرات السلوك والشذوذ المالي والمعرفة التنظيمية لتقديم توصية مخاطر دقيقة." : "Executes secure, on-device Local AI inference to analyze behavioral anomalies, rule signals, and regulatory nuances for high-precision risk recommendations."} /><Principle icon={<ShieldCheck />} title={isAr ? "حواجز وسياسات رقابية إلزامية" : "Mandatory policy guardrails"} text={isAr ? "تفرض القواعد التنظيمية حد أمان قطعي لا يمكن تجاوزه؛ فالمؤشرات عالية المخاطر تستدعي مراجعة بشرية إلزامية ولا يمكن لأي توصية خفض مستوى الأمان." : "Regulatory rules enforce an inviolable safety floor. High-risk indicators mandate human review, ensuring no AI recommendation can lower required compliance controls."} /></section>
    <section className="panel stages-panel methodology-journey"><div className="method-stage-heading"><div><span className="section-index">10</span><h3>{isAr ? "رحلة التحليل واستدلال الذكاء المحلي" : "The analysis & Local AI journey"}</h3><p>{isAr ? "أربع محطات متكاملة تجمع المراحل الأربع عشرة في تسلسل تقييم موحّد." : "Four comprehensive chapters group the 14 stages into one unified assessment sequence."}</p></div><span className="advisory-tag"><Sparkles size={13} /> {isAr ? "سجل قابل للتدقيق" : "AUDITABLE"}</span></div><div className="journey-chapters">{stageGroups.map((group, groupIndex) => <article className="journey-chapter" key={group.en}><div className="chapter-head"><span>{group.range}</span><h4>{isAr ? group.ar : group.en}</h4><i>{String(groupIndex + 1).padStart(2, "0")}</i></div><div className="chapter-steps">{group.indices.map(index => <span key={stages[index][0]}>{isAr ? stages[index][1] : stages[index][0]}</span>)}</div></article>)}</div></section>
    <section className="panel governance-references methodology-standards" aria-labelledby="methodology-standards-title"><div className="governance-references-heading"><div><span className="section-index">11</span><h3 id="methodology-standards-title"><Landmark size={17} />{isAr ? "أطر ومعايير التصميم المرجعية" : "Reference design standards"}</h3><p>{isAr ? "ثلاثة مراجع رئيسية بُنيت عليها مواءمة منهجية SentinelAI. يُمكن لاحقًا ربط كل إطار بمصفوفة تقرير توضح النقطة والدليل داخل النظام." : "Three primary references inform SentinelAI's methodological alignment. Each can later be linked to a report matrix that records the point and the system evidence."}</p></div><span className="governance-source-count">{isAr ? "3 أطر رئيسية" : "3 PRIMARY REFERENCES"}</span></div><div className="governance-reference-grid">{methodologyStandards.map(standard => <article className="governance-reference-card methodology-standard-card" key={standard.id}><div className="governance-reference-top"><span>{isAr ? standard.authorityAr : standard.authority}</span><ExternalLink size={15} aria-hidden="true" /></div><h4>{isAr ? standard.titleAr : standard.title}</h4><p className="methodology-standard-statement">{isAr ? standard.statementAr : standard.statement}</p><p>{isAr ? standard.useAr : standard.useEn}</p><div className="governance-reference-boundary"><small>{isAr ? "تركيز المواءمة" : "ALIGNMENT FOCUS"}</small><b>{isAr ? standard.boundaryAr : standard.boundaryEn}</b></div><button type="button" className="governance-reference-link" onClick={() => setExternalReference({ url: standard.url, label: isAr ? standard.titleAr : standard.title })}><ExternalLink size={13} aria-hidden="true" />{isAr ? "استعرض المصدر الرسمي" : "Open official source"}</button></article>)}</div></section>
    <section className="panel governance-references" aria-labelledby="governance-references-title"><div className="governance-references-heading"><div><span className="section-index">12</span><h3 id="governance-references-title"><Landmark size={17} />{isAr ? "المراجع التنظيمية المعتمدة" : "Approved regulatory references"}</h3><p>{isAr ? "توضح هذه المراجع نطاق السياق المستخدم في التحليل والحوكمة. يظل كل مصدر قابلاً للمراجعة من رابط رسمي مستقل." : "These references define the context used in analysis and governance. Each source remains reviewable through its independent official link."}</p></div><span className="governance-source-count">{isAr ? "3 مصادر معتمدة" : "3 CURATED SOURCES"}</span></div><div className="governance-reference-grid">{references.map(reference => <article className="governance-reference-card" key={reference.id}><div className="governance-reference-top"><span>{isAr ? reference.authorityAr : reference.authority}</span><ExternalLink size={15} aria-hidden="true" /></div><h4>{isAr ? reference.titleAr : reference.title}</h4><p>{isAr ? reference.useAr : reference.useEn}</p><div className="governance-reference-boundary"><small>{isAr ? "سياق الاستخدام" : "CONTEXT OF USE"}</small><b>{isAr ? reference.boundaryAr : reference.boundaryEn}</b></div><button type="button" className="governance-reference-link" onClick={() => setExternalReference({ url: reference.url, label: isAr ? reference.titleAr : reference.title })}><ExternalLink size={13} aria-hidden="true" />{isAr ? "استعرض المصدر الرسمي" : "Open official source"}</button></article>)}</div></section>
    <section className="panel governance-references customer-privacy-section" aria-labelledby="customer-privacy-title"><div className="governance-references-heading"><div><span className="section-index">13</span><h3 id="customer-privacy-title"><ShieldCheck size={17} />{isAr ? customerPrivacyPolicy.sectionTitleAr : customerPrivacyPolicy.sectionTitleEn}</h3><p>{isAr ? customerPrivacyPolicy.overviewAr : customerPrivacyPolicy.overviewEn}</p></div><span className="governance-source-count">{isAr ? "بيانات مقيدة الاستخدام" : "RESTRICTED USE"}</span></div><div className="customer-privacy-points">{customerPrivacyPolicy.points.map(point => <article className="customer-privacy-point" key={point.id}><div className="privacy-point-icon"><ShieldCheck size={15} /></div><div><b>{isAr ? point.titleAr : point.titleEn}</b><p>{isAr ? point.textAr : point.textEn}</p></div></article>)}</div><div className="customer-privacy-reference-wrapper"><article className="governance-reference-card customer-privacy-reference-card"><div className="governance-reference-top"><span>{isAr ? customerPrivacyPolicy.sdaiaReference.authorityAr : customerPrivacyPolicy.sdaiaReference.authority}</span><span className="governance-reference-badge">{isAr ? customerPrivacyPolicy.sdaiaReference.alignmentTypeAr : customerPrivacyPolicy.sdaiaReference.alignmentTypeEn}</span></div><h4>{isAr ? customerPrivacyPolicy.sdaiaReference.cardTitleAr : customerPrivacyPolicy.sdaiaReference.cardTitleEn}</h4><p className="customer-privacy-reference-statement">{isAr ? customerPrivacyPolicy.sdaiaReference.statementAr : customerPrivacyPolicy.sdaiaReference.statementEn}</p><div className="customer-privacy-principles-grid">{customerPrivacyPolicy.sdaiaReference.principles.map(principle => <div className="customer-privacy-principle-item" key={principle.id}><strong>{isAr ? principle.titleAr : principle.titleEn}</strong><span>{isAr ? principle.textAr : principle.textEn}</span></div>)}</div><div className="governance-reference-boundary"><small>{isAr ? "تركيز المواءمة والحوكمة" : "GOVERNANCE & ALIGNMENT FOCUS"}</small><b>{isAr ? customerPrivacyPolicy.sdaiaReference.boundaryAr : customerPrivacyPolicy.sdaiaReference.boundaryEn}</b></div><button type="button" className="governance-reference-link" onClick={() => setExternalReference({ url: customerPrivacyPolicy.sdaiaReference.url, label: isAr ? customerPrivacyPolicy.sdaiaReference.cardTitleAr : customerPrivacyPolicy.sdaiaReference.cardTitleEn })}><ExternalLink size={13} aria-hidden="true" />{isAr ? "استعرض المصدر الرسمي (سدايا)" : "Open official source (SDAIA)"}</button></article></div></section>
    <DecisionQualityEvidencePanel />
    <Dialog open={Boolean(externalReference)} onOpenChange={open => { if (!open) setExternalReference(null); }}><DialogContent className="external-confirm-dialog"><DialogTitle>{isAr ? "فتح مصدر خارجي؟" : "Open an external source?"}</DialogTitle><DialogDescription>{isAr ? "ستنتقل إلى مصدر رسمي في علامة تبويب جديدة خارج SentinelAI." : "You will open an official source in a new tab outside SentinelAI."}</DialogDescription><p className="external-confirm-url">{externalReference?.label}</p><DialogFooter><button type="button" className="secondary-button" onClick={() => setExternalReference(null)}>{isAr ? "إلغاء" : "Cancel"}</button><button type="button" className="primary-button" onClick={() => { if (externalReference) window.open(externalReference.url, "_blank", "noopener,noreferrer"); setExternalReference(null); }}>{isAr ? "متابعة إلى المصدر" : "Continue to source"}</button></DialogFooter></DialogContent></Dialog>
  </SentinelLayout>;
}

function Principle({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) {
  return <div>{icon}<h3>{title}</h3><p>{text}</p></div>;
}
